/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProtectedRoute2RouteImport } from './routes/protected-route2'
import { Route as ProtectedRouteRouteImport } from './routes/protected-route'
import { Route as MapDemoRouteImport } from './routes/map-demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute2Route = ProtectedRoute2RouteImport.update({
  id: '/protected-route2',
  path: '/protected-route2',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/protected-route',
  path: '/protected-route',
  getParentRoute: () => rootRouteImport,
} as any)
const MapDemoRoute = MapDemoRouteImport.update({
  id: '/map-demo',
  path: '/map-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map-demo': typeof MapDemoRoute
  '/protected-route': typeof ProtectedRouteRoute
  '/protected-route2': typeof ProtectedRoute2Route
  '/register': typeof RegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map-demo': typeof MapDemoRoute
  '/protected-route': typeof ProtectedRouteRoute
  '/protected-route2': typeof ProtectedRoute2Route
  '/register': typeof RegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map-demo': typeof MapDemoRoute
  '/protected-route': typeof ProtectedRouteRoute
  '/protected-route2': typeof ProtectedRoute2Route
  '/register': typeof RegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/map-demo'
    | '/protected-route'
    | '/protected-route2'
    | '/register'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map-demo'
    | '/protected-route'
    | '/protected-route2'
    | '/register'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/map-demo'
    | '/protected-route'
    | '/protected-route2'
    | '/register'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MapDemoRoute: typeof MapDemoRoute
  ProtectedRouteRoute: typeof ProtectedRouteRoute
  ProtectedRoute2Route: typeof ProtectedRoute2Route
  RegisterRoute: typeof RegisterRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected-route2': {
      id: '/protected-route2'
      path: '/protected-route2'
      fullPath: '/protected-route2'
      preLoaderRoute: typeof ProtectedRoute2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected-route': {
      id: '/protected-route'
      path: '/protected-route'
      fullPath: '/protected-route'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-demo': {
      id: '/map-demo'
      path: '/map-demo'
      fullPath: '/map-demo'
      preLoaderRoute: typeof MapDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MapDemoRoute: MapDemoRoute,
  ProtectedRouteRoute: ProtectedRouteRoute,
  ProtectedRoute2Route: ProtectedRoute2Route,
  RegisterRoute: RegisterRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
